---
all:
  hosts:
    sql_server_machine:
      ansible_host: 192.168.68.84
      ansible_port: 22
      ansible_user: guest
      ansible_password: guest
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: guest

    backends_machine:
      ansible_host: 192.168.68.55
      ansible_port: 22
      ansible_user: guest
      ansible_password: guest
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: guest

    frontends_machine:
      ansible_host: 192.168.68.83
      ansible_port: 22
      ansible_user: guest
      ansible_password: guest
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: guest



